services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/flowtestify-db
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000/api # URL del backend
    depends_on:
      - backend

volumes:
  mongo-data:
