services:
  backend:
    build: ./backend
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/flowtestify-db
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  playwright:
    build: ./playwright
    ports:
      - "3003:3003"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
