services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/flowtestify-db
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3001:3000" # React di default usa la porta 3000, ma la esponiamo su 3001 per evitare conflitti
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000/api # URL del backend per le chiamate API
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
