services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/flowtestify-db
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"   # Esponi il frontend su porta 8080
    environment:
      - REACT_APP_API_URL=http://backend:3000/api  # URL del backend (se applicabile)
    depends_on:
      - backend  # Se hai un backend separato
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
